version: 0.2
env:
  variables:
    INDY_ENV: test
phases:
  install:
    runtime-versions:
        ruby: 2.7
  pre_build:
    commands:
      - gem install bundler
      - bundle config set without development
      - bundle exec rspec
  build:
    commands:
      - echo Building SHA $CODEBUILD_RESOLVED_SOURCE_VERSION
      - rspec spec/ --format RspecJunitFormatter --out out/report.xml
      - echo "\$my_git_commit_sha = '$CODEBUILD_RESOLVED_SOURCE_VERSION'" > git_commit_sha.rb
      - export BUCKET=indybooks-lambda-deployment-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
  post_build:
    commands:
      - echo post build ran at `date`
reports:
    rspec_reports:
        files:
            - report.xml
        base-directory: out
        file-format: JunitXml
artifacts:
  files:
    - '**/*'
