version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.7
  build:
    commands:
      - export BUCKET=indybooks-lambda-deployment-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
      - echo "\$my_git_commit_sha = '$CODEBUILD_RESOLVED_SOURCE_VERSION'" > git_commit_sha.rb
  post_build:
    commands:
      - echo post build ran at `date`
artifacts:
  files:
    - '**/*'
