AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the store list
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  StoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_stores_production
      Handler: stores/index.stores_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /stores/{proxy+}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  OffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_inventory_production
      Handler: offers/index.offers_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /offers/{proxy+}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  PurchasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_purchases_production
      Handler: purchases/index.purchases_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /purchases/{proxy+}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  PurchasesPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBWritePolicy:
            TableName: indybooks_purchases_production
      Handler: purchases_post/index.purchases_post_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /purchases
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi


