AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the store list
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
  StoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: ruby2.7
      CodeUri: ./
      Cors: "'*'"
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /stores
            Method: GET
            
