AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API for the Indybooks backend
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,POST,PUT'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          MyCognitoAuth:
            UserPoolArn: arn:aws:cognito-idp:us-east-2:308748601361:userpool/us-east-2_WKijNuDww
            Identity:
              Header: Authorization
  StoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_stores_production
      Handler: lambda/stores/get.stores_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /stores/{proxy+}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  OffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_inventory_production
      Handler: lambda/offers/get.offers_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /offers/{proxy+}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  PurchasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_purchases_production
      Handler: lambda/purchases/get.purchases_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /purchases/{proxy+}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  PurchasesPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBWritePolicy:
            TableName: indybooks_purchases_production
      Handler: lambda/purchases/post.purchases_post_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /purchases
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi
  AuthMyStoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
      Handler: lambda/auth/my/stores/get.auth_my_stores_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/my/stores
            Method: GET
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi
  AuthInventoryStoreIsbn:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
          ISBN_SECRET: '{{resolve:secretsmanager:com.isbndb.api2.auth.v2:SecretString:secret}}'
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_inventory_production
      Handler: lambda/auth/inventory/store/isbn/get.auth_inventory_store_isbn_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/inventory/{proxy+}
            Method: GET
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi
  AuthInventoryStoreIsbnPut:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBWritePolicy:
            TableName: indybooks_inventory_production
      Handler: lambda/auth/inventory/store/isbn/put.auth_inventory_store_isbn_put_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/inventory/{proxy+}
            Method: PUT
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi
  AuthPilePost:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBWritePolicy:
            TableName: indybooks_piles_production
        - DynamoDBWritePolicy:
            TableName: indybooks_user_piles_production
      Handler: lambda/auth/pile/post.piles_post_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/pile
            Method: POST
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi
  AuthPilesGet:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_piles_production
      Handler: lambda/auth/pile/get.auth_pile_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/pile/{proxy+}
            Method: GET
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi
  AuthPilesPut:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBWritePolicy:
            TableName: indybooks_piles_production
      Handler: lambda/auth/pile/put.auth_pile_put_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/pile/{proxy+}
            Method: PUT
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi
  AuthMyPileGet:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_user_piles_production
      Handler: lambda/auth/my/pile/get.auth_my_pile_get_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /auth/my/pile
            Method: GET
            Auth:
               Authorizer: MyCognitoAuth
            RestApiId:
              Ref: ApiGatewayApi


