AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the store list
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
  StoresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Policies:
        - DynamoDBReadPolicy:
            TableName: indybooks_inventory_production
        - KMSDecryptPolicy:
            KeyId: arn:aws:kms:us-east-2:308748601361:key/59025e18-f6a2-43e2-abf9-7a811aaf3296
        - KMSEncryptPolicy:
            KeyId: arn:aws:kms:us-east-2:308748601361:key/59025e18-f6a2-43e2-abf9-7a811aaf3296
      Handler: index.handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /stores
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  OffersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          INDY_ENV: production
      Handler: offers/index.offers_handler
      Runtime: ruby2.7
      CodeUri: ./
      Events:
        StoresAPI:
          Type: Api
          Properties:
            Path: /offers
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi


